SELECT DISTINCT 'configurable' as type,
'admin' as store,
'base' as websites,
lcv.CodeArticleLCV as sku,
'Chaussure' as attribute_set,
1 as 'has_options',
CONCAT(mev.marque,' ',mev.model_label,' (',mev.Couleur,')') as name,
CONCAT(mev.marque,' ',mev.model_label,' (',mev.Couleur,')') as title,
mev.description as meta_description,
mev.Price as price,
mev.Cost as cost,
'TVA' as tax_class_id,
'container2' as options_container,
1 as status,
4 as visibility,
mev.description as description,
mev.description as short_description,
0 as qty,
mev.marque as manufacturer,
mev.Couleur as color,
mev.Chaussant as chaussant,
mev.Exterieur as exterieur,
mev.Interieur as interieur,
mev.Semelle as semelle,
mev.Talon as hauteur_talon,
mev.img1 as image,
mev.img1 as small_image,
mev.img1 as thumbnail,
CONCAT(mev.img2,';',mev.img3,';',mev.img4,';',mev.img5,';',mev.img6) as media_gallery,
CONCAT('Chaussures ',
		CONCAT(UPPER(SUBSTRING(mev.Rayon, 1, 1)), LOWER(SUBSTRING(mev.Rayon FROM 2))),
		'/',
		CONCAT(UPPER(SUBSTRING(mev.Famille, 1, 1)), LOWER(SUBSTRING(mev.Famille FROM 2)))) as categories

FROM ms_import_lcv as lcv
JOIN ms_import_mevia as mev ON mev.CodeArticleLCV=lcv.CodeArticleLCV