SELECT p.Title as name,
p.Title as description,
p.idProduct as sku,
p.Cover as image,
p.Cover as small_image,
p.Cover as thumbnail,
IF(p.Active,1,2) as status,
p.Price as price,
p.CostPrice as cost,
p.SpecialPrice as special_price,
p.SupplierStock as qty,
4 as visibility,
'zzz' as tax_class_id,
'Default' as attribute_set,
'admin' as store,
'base' as websites,
'simple' as type,
CONCAT("Toys/",c.catName) as categories
FROM products as p
JOIN cat_product as cp ON cp.idProduct=p.idProduct
JOIN cats as c ON cp.idCat=c.idCat